# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-24 18:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(db_column='id_authors', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('family_name', models.TextField(blank=True, null=True)),
                ('birth', models.IntegerField(blank=True, null=True)),
                ('death', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name', 'family_name', 'birth'],
                'db_table': 'authors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(db_column='id_books', primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('year', models.IntegerField(null=True)),
                ('author', models.ForeignKey(db_column='id_authors', on_delete=django.db.models.deletion.DO_NOTHING, to='books.Author')),
            ],
            options={
                'ordering': ['title', 'author'],
                'db_table': 'books',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FileBooks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('formats', models.CharField(choices=[('PDF', 'PDF'), ('ODT', 'ODT'), ('DOCX', 'DOCX'), ('EPUB', 'EPUB'), ('MOBI', 'MOBI'), ('DOC', 'DOC')], default='ODT', max_length=4)),
                ('book', models.ForeignKey(db_column='id_books', on_delete=django.db.models.deletion.DO_NOTHING, to='books.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ES', 'Español'), ('EN', 'English'), ('FR', 'Francés')], default='EN', max_length=2)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Valoration',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('valoration', models.IntegerField(blank=True, null=True)),
                ('read_start', models.DateField(blank=True, null=True)),
                ('read_end', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(db_column='id_books', on_delete=django.db.models.deletion.DO_NOTHING, to='books.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['valoration', 'read_end'],
                'db_table': 'valorations',
                'managed': True,
            },
        ),
    ]
