# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-05 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('ES', 'Español'), ('EN', 'English'), ('FR', 'Francés')], default='EN', max_length=2),
        ),
    ]
