# Generated by Django 3.0.8 on 2020-07-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20180722_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Man'), (1, 'Woman')], default=0, verbose_name='Gender'),
        ),
    ]
