# Generated by Django 3.1 on 2020-08-06 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_author_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'managed': True, 'ordering': ['name', 'family_name', 'birth', 'death', 'gender']},
        ),
    ]
