# Generated by Django 3.1 on 2020-08-07 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20200807_0805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('statistics_global', 'Can see global statistics'), ('statistics_user', 'Can see user statistics'), ('search_book', 'Can search books'), ('search_author', 'Can search authors'), ('search_valoration', 'Can search valorations'))},
        ),
    ]
