# Generated by Django 3.1 on 2020-08-07 08:05

from django.db import migrations
from django.contrib.auth.models import Group, Permission
def apply_migration(apps, schema_editor):

    group = Group.objects.get(name="Default library workers")
    permissions = Permission.objects.filter(codename__in = [
        'change_book','add_book','delete_book','search_book', 
        'change_author','add_author','delete_author','search_author', 
        'change_valoration','add_valoration','delete_valoration','search_valoration', 
    ])
    group.permissions.add(*permissions)
    
    group = Group.objects.get(name="Default library users")
    permissions = Permission.objects.filter(codename__in = [
        'search_book', 
        'search_author', 
        'change_valoration','add_valoration','delete_valoration','search_valoration', 
    ])
    group.permissions.add(*permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20200807_0836'),
    ]


    operations = [
        migrations.RunPython(apply_migration),
    ]
