# Generated by Django 3.1 on 2020-08-07 09:01

from django.db import migrations

from django.contrib.auth.models import Group, Permission
def apply_migration(apps, schema_editor):

    group = Group.objects.get(name="Default library workers")
    permissions = Permission.objects.filter(codename__in = [
        'statistics_user','statistics_global',
    ])
    group.permissions.add(*permissions)
    
    group = Group.objects.get(name="Default library users")
    permissions = Permission.objects.filter(codename__in = [
        'statistics_user',
    ])
    group.permissions.add(*permissions)







class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_mine_20200807_0859_permissions_to_groups'),
    ]

    operations = [
        migrations.RunPython(apply_migration),
    ]
