# Generated by Django 3.1 on 2020-08-20 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_remove_profile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoration',
            name='read_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date read started'),
        ),
    ]
