# Generated by Django 3.1 on 2020-08-21 04:21

from django.db import migrations
from django.contrib.auth.management import create_permissions
from django.contrib.auth.models import Group, Permission

def create_perms(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None

def assign_perms(apps, schema_editor):

    group = Group.objects.get(name="Default library workers")
    permissions = Permission.objects.filter(codename__in = [
        'view_book', 'change_book', 'add_book', 'delete_book', 'search_book', 
        'view_author', 'change_author', 'add_author', 'delete_author', 'search_author', 
        'view_valoration', 'change_valoration', 'add_valoration', 'delete_valoration', 'search_valoration',
        'statistics_global', 'statistics_user',
    ])
    group.permissions.add(*permissions)
    
    group = Group.objects.get(name="Default library users")
    permissions = Permission.objects.filter(codename__in = [
        'search_book', 
        'search_author',
        'search_valoration', 'change_valoration','add_valoration','delete_valoration','view_valoration', 
    ])
    group.permissions.add(*permissions)



class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20200820_1804'),
    ]

    operations = [
        migrations.RunPython(create_perms), #Creates permissions of other migrations. Needs this explicit
        migrations.RunPython(assign_perms)
    ]
